# -*- coding: utf-8 -*-
"""flowability steamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170z523OIZu0bukltGwZuIeQD_YRWYpKp
"""

import re
import pandas as pd
import streamlit as st

# 1. Load Excel Data
@st.cache_data
def load_data():
    return pd.read_excel("reference value of flowability.xlsx", sheet_name="Sheet1")

try:
    reference = load_data()
except Exception as e:
    st.error(f"Please ensure 'reference value of flowability.xlsx' is in your repository. Error: {e}")
    st.stop()

# 2. Helper Functions
def value_in_range(value, range_text):
    text = str(range_text).strip().lower().replace(" ", "")

    if "-" in text:
        parts = text.split("-")
        if len(parts) == 2:
            try:
                return float(parts[0]) <= value <= float(parts[1])
            except:
                pass

    if "to" in text:
        parts = text.split("to")
        if len(parts) == 2:
            try:
                return float(parts[0]) <= value <= float(parts[1])
            except:
                pass

    if "≤" in text:
        try:
            return value <= float(text.replace("≤", ""))
        except:
            pass

    if "≥" in text:
        try:
            return value >= float(text.replace("≥", ""))
        except:
            pass

    if text.startswith(">"):
        try:
            return value > float(text.replace(">", ""))
        except:
            pass

    return False

def find_category(value, column_number):
    for _, row in reference.iterrows():
        range_text = row.iloc[column_number]
        if value_in_range(value, range_text):
            return str(row.iloc[0]).strip().title()
    return "Outside Reference Range"

def analyze_flow(angle, carr, hausner):
    angle_result = find_category(angle, 1)
    carr_result = find_category(carr, 2)
    hausner_result = find_category(hausner, 3)

    results = [angle_result, carr_result, hausner_result]
    valid_results = [r for r in results if r != "Outside Reference Range"]

    if len(valid_results) == 0:
        final_result = "No valid classification"
    else:
        counts = pd.Series(valid_results).value_counts()
        if counts.iloc[0] >= 2:
            final_result = counts.index[0]
        else:
            final_result = "Review Required"

    return angle_result, carr_result, hausner_result, final_result

# 3. Streamlit Web UI
st.title("🧪 AI-Assisted Powder Flowability Analyzer")
st.write("Enter the three laboratory measurements. The system compares each value with the reference ranges stored in the Excel file.")

col1, col2, col3 = st.columns(3)
with col1:
    angle = st.number_input("1. Angle of Repose (°)", value=0.0)
with col2:
    carr = st.number_input("2. Carr's Index (%)", value=0.0)
with col3:
    hausner = st.number_input("3. Hausner Ratio", value=0.0)

if st.button("Analyze Flowability"):
    angle_res, carr_res, hausner_res, final_res = analyze_flow(angle, carr, hausner)

    st.subheader("Results")
    st.write(f"**Angle of Repose Classification:** {angle_res}")
    st.write(f"**Carr's Index Classification:** {carr_res}")
    st.write(f"**Hausner Ratio Classification:** {hausner_res}")
    st.success(f"**FINAL FLOWABILITY PREDICTION:** {final_res}")